name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        # intentionally not using cache to avoid corrupted caches

    - name: Clean npm cache (fix integrity errors)
      run: npm cache clean --force

    - name: Verify npm cache
      run: npm cache verify || true

    - name: Install dependencies
      run: |
        # If a lockfile exists, use npm ci for deterministic installs.
        # If no lockfile exists, generate a package-lock.json then use npm ci.
        if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
          echo "Lockfile found, using npm ci"
          npm ci
        else
          echo "No lockfile found, generating package-lock.json and installing"
          npm install --package-lock-only 
          npm ci
        fi

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
